Repository Kusitms-26th-Ohttention/pickRAP-FE, pull requests merged in 2023-01, with the labels that each got.

#39 :sparkles: Feat: 스크랩 상세 페이지 하이퍼링크
  src/components/scrap/Content/SwipeBackground.tsx
  src/pages/scrap/[id].tsx
Labels: feature

#41 Design: 매거진 첫 페이지 프로필 UI 스타일링
  src/components/magazine/MagazinePageProfile/index.tsx
  src/containers/magazine/PageViewContainer.tsx
  src/pages/magazine/[id].tsx
Labels: design

#38 Feat: 매거진 관리 : 삭제 기능
  src/application/store/magazine/hook.ts
  src/application/store/magazine/state.ts
  src/components/magazine/MagazineList/TabMagazine.tsx
  src/containers/magazine/TabMagazineViewContainer.tsx
  src/infra/api/magazine.ts
Labels: feature

#44 ✨ Feat : 비디오/PDF 콘텐츠 렌더링 & 클릭 시 전체화면
  package.json
  src/application/hooks/common/useWindowSize.ts
  src/application/store/scrap/useScrapForm.ts
  src/application/utils/constant.ts
  src/application/utils/helper.ts
  src/components/scrap/Content/PdfViewer.tsx
  src/components/scrap/Content/SwipeBackground.tsx
  src/components/scrap/Content/SwipeSection.tsx
  src/components/scrap/Toast/CreateScrap.tsx
  src/pages/scrap/[id].tsx
  yarn.lock
Labels: feature

#42 :lipstick: 매거진 페이지 삭제 UI 스타일링/삭제 기능 제작
  src/application/store/magazine/hook.ts
  src/application/store/magazine/state.ts
  src/components/magazine/PageList/index.tsx
  src/containers/magazine/MagazineCreateContainer.tsx
  src/containers/magazine/PageViewContainer.tsx
  src/infra/api/magazine.ts
  src/pages/magazine/edit/[id].tsx
  src/types/index.d.ts
Labels: feature, design

#43 :sparkles: Feat: 스크랩/카테고리 삭제 기능
  src/application/hooks/api/category/index.ts
  src/application/hooks/api/scrap/index.ts
  src/application/store/category/categoryHook.ts
  src/application/store/category/categoryState.ts
  src/application/store/magazine/hook.ts
  src/application/store/magazine/state.ts
  src/application/store/scrap/scrapHook.ts
  src/application/store/scrap/scrapState.ts
  src/application/utils/helper.ts
  src/containers/magazine/TabMagazineViewContainer.tsx
  src/containers/scrap/CategoryDetailContainer.tsx
  src/containers/scrap/CategoryListContainer.tsx
  src/containers/scrap/ContentListContainer.tsx
  src/containers/scrap/PhotoListContainer.tsx
  src/infra/api/scrap.ts
  src/infra/api/types/scrap.ts
  src/pages/magazine/index.tsx
  src/pages/scrap/index.tsx
Labels: feature

#46 Feat: 내 스크랩 분석 UI스타일링, API 호출
  src/application/hooks/api/analysis/index.ts
  src/application/store/analysis/analysisHook.ts
  src/application/store/analysis/analysisState.ts
  src/components/analysis/ AnaNavigation/AnalysisNavigation.tsx
  src/components/analysis/AnaNavigation/AnalysisNavigation.tsx
  src/components/analysis/AnaNavigation/SubAnaNavigation.tsx
  src/components/analysis/NoAnalysis/index.tsx
  src/components/analysis/PersonalMoodContent.tsx
  src/components/analysis/RevisitContent.tsx
  src/components/analysis/SelectPeriod/YearMonthList.tsx
  src/components/analysis/SelectPeriod/YearMonthSelector.tsx
  src/components/analysis/SelectPeriod/index.tsx
  src/components/analysis/TagAnalysisContent.tsx
  src/components/analysis/TextAnalysisContent.tsx
  src/components/common/Chip/index.tsx
  src/containers/analysis/AnalysisListContainer.tsx
  src/containers/analysis/RevisitAnalysis/RevisitAnalysisDetail.tsx
  src/containers/analysis/TagAnalysis/TagAnalysisContainer.tsx
  src/containers/analysis/TagAnalysis/TagAnalysisDetail.tsx
  src/containers/analysis/TagAnalysis/TagDetailContainer.tsx
  src/infra/api/analysis.ts
  src/infra/api/types/analysis.ts
  src/pages/analysis/index.tsx
  src/styles/font.ts
Labels: feature, design
