Repository Kusitms-26th-Ohttention/pickRAP-FE, pull requests merged in 2023-03, with the labels that each got.

#55 :lipstick: QA: UXUI 변경
  src/application/store/analysis/analysisState.ts
  src/components/analysis/SelectPeriod/index.tsx
  src/components/category/Select/SelectCategoryWithCreate.tsx
  src/components/common/Popup/Sentence.tsx
  src/components/common/Popup/Template.tsx
  src/components/common/Popup/index.tsx
  src/components/scrap/Toast/CreateScrap.tsx
  src/containers/analysis/TagAnalysis/TagAnalysisDetail.tsx
  src/containers/magazine/PageEditContainer.tsx
  src/containers/scrap/CategoryDetailContainer.tsx
  src/pages/magazine/upload/page.tsx
Labels: fix, design

#54 Fix: QA 스크랩 관련 요소 수정
  src/application/hooks/common/useInput.ts
  src/components/category/Modal/CreateCategory.tsx
  src/components/category/Select/SelectCategoryWithCreate.tsx
  src/components/common/Modal/Input.tsx
  src/components/scrap/Toast/CreateScrap.tsx
  src/components/scrap/Toast/TypedComplete.tsx
  src/containers/scrap/CategoryDetailContainer.tsx
  src/containers/scrap/CategoryListContainer.tsx
  src/pages/scrap/[id].tsx
Labels: bug, fix

#53 Fix: QA 매거진 관련 요소 수정
  src/application/store/magazine/state.ts
  src/application/utils/mock.ts
  src/components/common/Popup/MagazineWarningSentence.tsx
  src/components/common/Toast/ui/Input.tsx
  src/components/magazine/MagazineList/TabMagazine.tsx
  src/components/magazine/PageList/index.tsx
  src/containers/magazine/MagazineCreateContainer.tsx
  src/containers/magazine/PageEditContainer.tsx
  src/containers/magazine/PageViewContainer.tsx
  src/containers/magazine/TabMagazineViewContainer.tsx
  src/pages/magazine/edit/[id].tsx
  src/pages/magazine/upload/index.tsx
  src/pages/magazine/upload/page.tsx
  src/pages/scrap/index.tsx
  src/types/index.d.ts
Labels: bug, fix, design

#56 Design: 탐색페이지 검색 시 UI 스타일링
  src/application/utils/mock.ts
  src/components/common/Photo/index.tsx
  src/containers/search/SearchListContainer.tsx
  src/containers/search/SearchPhotoListContainer.tsx
  src/pages/search/index.tsx
Labels: design

#57 🐛 인증, 매거진 qa
  .husky/pre-commit
  package.json
  src/application/hooks/api/auth/useSNSLogin.ts
  src/application/store/magazine/hook.ts
  src/components/auth/OAuthButton.tsx
  src/components/magazine/PageList/index.tsx
  src/components/scrap/Toast/TypedComplete.tsx
  src/containers/magazine/PageEditContainer.tsx
  src/containers/magazine/PageViewContainer.tsx
  src/infra/api/instance.ts
  src/pages/auth/kakao/callback.tsx
  src/pages/auth/naver/callback.tsx
  src/pages/auth/signin.tsx
  src/pages/auth/signup.tsx
  src/pages/index.tsx
  src/pages/magazine/upload/index.tsx
  src/pages/magazine/upload/page.tsx
  src/pages/scrap/index.tsx
  yarn.lock
Labels: fix
